# Generated by Django 5.2.14 on 2026-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('shift', 'Shift'), ('training', 'Training'), ('off', 'Off')], max_length=50)),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('absent', 'Absent')], max_length=50)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('availability_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
